server:
  port: 8080
  servlet:
    context-path: /ems
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Tokyo
    username: root
    password: root


  web:
    resources:
      static-locations: classpath:/static/,file:${resume.file.dir} //暴露哪些资源可以通过项目名访问

resume:
  file:
    dir: E:\桌面\ems-Thymeleaf\code\EM-System\resume

mybatis:
  mapper-locations: classpath:com/thymeleaf/mapper/*.xml
  type-aliases-package: com.thymeleaf.entity
page helper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params:

logging:
  level:
    root: info
    com.thymeleaf: debug

